{{- range $s := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $s.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "envoy.labels" $ | nindent 4 }}
{{- with $s.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ $s.type }}
  ports: {{ $s.ports | toYaml | nindent 4 }}
  {{- with $s.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    {{- include "envoy.selectorLabels" $ | nindent 4 }}
{{- end }}
